/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FmcwxAnvZ7n
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function EditComponent() {
  return (
    <Card className="max-w-3xl mx-auto p-8 bg-white shadow-md rounded-lg">
      <CardHeader>
        <CardTitle>Edit SQL Record</CardTitle>
        <CardDescription>Update the existing record in the database.</CardDescription>
      </CardHeader>
      <CardContent>
        <form>
          <div className="grid gap-4">
            <div className="flex flex-col space-y-1.5">
              <Label htmlFor="primaryKey">Primary Key</Label>
              <Input
                className="bg-[#f0f1f3] cursor-not-allowed"
                disabled
                id="primaryKey"
                placeholder="Primary Key"
                type="text"
              />
            </div>
            <div className="flex flex-col space-y-1.5">
              <Label htmlFor="column1">Column 1</Label>
              <Input id="column1" placeholder="Enter value" type="text" />
            </div>
            <div className="flex flex-col space-y-1.5">
              <Label htmlFor="column2">Column 2</Label>
              <Input id="column2" placeholder="Enter value" type="number" />
            </div>
            <div className="flex flex-col space-y-1.5">
              <Label htmlFor="column3">Column 3</Label>
              <Input id="column3" placeholder="Enter value" type="date" />
            </div>
          </div>
        </form>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button variant="outline">Cancel</Button>
        <Button className="ml-4" type="submit">
          Save changes
        </Button>
      </CardFooter>
    </Card>
  )
}
